// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD-UFUpreQMPzbgwiBD2yOGEf33gZCb18',
    appId: '1:908010826379:web:654857d3dcc6ffe63d028e',
    messagingSenderId: '908010826379',
    projectId: 'ghuma-d3d44',
    authDomain: 'ghuma-d3d44.firebaseapp.com',
    storageBucket: 'ghuma-d3d44.appspot.com',
    measurementId: 'G-ZV3JVS6F1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuH3vUu8ZhHfUQgOria-GcRN2TehGixlY',
    appId: '1:908010826379:android:f7445da59a11fa493d028e',
    messagingSenderId: '908010826379',
    projectId: 'ghuma-d3d44',
    storageBucket: 'ghuma-d3d44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq9A5ZFgVGGEuBDeNMcvMOiLnIYzOVlNU',
    appId: '1:908010826379:ios:5c218653416942bf3d028e',
    messagingSenderId: '908010826379',
    projectId: 'ghuma-d3d44',
    storageBucket: 'ghuma-d3d44.appspot.com',
    iosBundleId: 'com.example.adminGhuma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq9A5ZFgVGGEuBDeNMcvMOiLnIYzOVlNU',
    appId: '1:908010826379:ios:5c218653416942bf3d028e',
    messagingSenderId: '908010826379',
    projectId: 'ghuma-d3d44',
    storageBucket: 'ghuma-d3d44.appspot.com',
    iosBundleId: 'com.example.adminGhuma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD-UFUpreQMPzbgwiBD2yOGEf33gZCb18',
    appId: '1:908010826379:web:20772152b41bdb313d028e',
    messagingSenderId: '908010826379',
    projectId: 'ghuma-d3d44',
    authDomain: 'ghuma-d3d44.firebaseapp.com',
    storageBucket: 'ghuma-d3d44.appspot.com',
    measurementId: 'G-9N7BX4YV14',
  );
}
